# Generated by Django 2.2.9 on 2022-07-19 09:25

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220719_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('pub_date'), descending=True, nulls_last=True)]},
        ),
    ]
